theme: jekyll-theme-architect

title: [metro-fi]
description: [Metro Subproject: Binary encoding for the XML Information Set]

# sidebar links url
links:
  source: https://github.com/javaee/metro-fi
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

